// <auto-generated />
using System;
using Biblioteka.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteka.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906055601_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Biblioteka.Domain.Czytelnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaszHasla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Czytelnicy");
                });

            modelBuilder.Entity("Biblioteka.Domain.Ksiazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LiczbaEgzemplarzy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ksiazki");
                });

            modelBuilder.Entity("Biblioteka.Domain.Wypozyczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CzytelnikId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("TEXT");

                    b.Property<int>("KsiazkaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KsiazkaId", "CzytelnikId", "DataWypozyczenia");

                    b.ToTable("Wypozyczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
